- features/pom.xml
- plugins/pom.xml
- site/pom.xml
- tests/pom.xml
> JBIDE-26816: Update bundles ids of the Quarkus plugins/feature to org.jboss.tools.quarkus.* - Remove unneeded group id tags

- plugins/org.jboss.tools.quarkus.lsp4e/plugin.xml
- plugins/org.jboss.tools.quarkus.lsp4e/pom.xml
> Use latest quarkus-ls 0.0.4 + remove content type mapping for Java files

- plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectWizardController.java
> JBIDE-27080: Project wizard fails on Windows

- plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectTypeWizardPage.java
- plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectWizard.java
- Added additional checks for Gradle projects
> JBIDE-27057: rootProject.name in Gradle Project is incorrect

- itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/AbstractLaunchConfigurationTest.java
- itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/CreateNewQuarkusConfigurationGradleTest.java
- itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/CreateNewQuarkusConfigurationMavenTest.java
- itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/AbstractCreateNewProjectTest.java
- itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/CreateNewProjectTest.java
- itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/InstallQuarkusExtensionTest.java
- test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/common/QuarkusLabels.java
https://quarkus.io/blog/quarkus-1-3-1-final-released/
Created AbstractCreateNewProjectTest ,changed CreateNewProjectTest,
InstallQuarkusExtensionTest and
QuarkusLabels. Added check jdk for
CreateNewQuarkusConfiguration(Gradle|Maven)Test.
> JBIDE-27182: Reworked "create new quarkus project" cause of

- plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/launch/LaunchUtils.java
> JBIDE-27283: Run configuration seems to trigger build for all projects

- plugins/org.jboss.tools.quarkus.runtime/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.quarkus.runtime/pom.xml
- pom.xml
> JBIDE-27325: jbosstools-quarkus is using own jackson jars, use from TP

- tests/org.jboss.tools.quarkus.lsp4e.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.quarkus.lsp4e.test/pom.xml
- tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/JDTConfigItemIntBoolDefaultValueTest.java
- tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/JDTMicroProfileConfigPropertyTest.java
> JBIDE-27425: quarkus build fails on Java8

- features/org.jboss.tools.quarkus.feature/feature.xml
- tests/org.jboss.tools.quarkus.lsp4e.test/META-INF/MANIFEST.MF
> revert as bundle is not present in TP yet and fails in downstream builds

- plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/yaml/SchemaRegistry.java
> JBIDE-27462: YAML code assist works only once

- plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/launch/LaunchUtils.java
> JBIDE-27603: NPE when Quarkus configuration project is closed or deleted

- pom.xml
> JBIDE-27713: quarkus build failing with 2021-03 TP

- plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/launch/QuarkusLaunchConfigurationTabGroup.java
- pom.xml
> JBIDE-27738: Allow environment variables for Quarkus configurations

- itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/AbstractContentAssistantTest.java
- itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectsOnOtherPorts.java
- itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/universal/methods/AbstractQuarkusTest.java
open file with text editor from AbstractCAtest to AbstractQuarkusTest
> JBIDE-27799: added more time for loading microprofile, moved method for

- pom.xml
> JBIDE-27783: Remove jdt-quarkus from jbosstools-quarkus

- features/org.jboss.tools.quarkus.feature/feature.xml
> JBIDE-28202: Wild Web Developer node fragments not in update sites

- plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/properties/qute/QuteConfigurationBlock.java
> JBIDE-28474: Label for excludes Qute templates setting is absent

- plugins/org.jboss.tools.quarkus.lsp4e/plugin.xml
> JBIDE-28494: Can't open application.properties on Windows

- plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/tool/GradleToolSupport.java
- plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/tool/MavenToolSupport.java
> JBIDE-28715: Quarkus run configurations starts the Java debugger

- plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageServer.java
debug port with system property like
`-Dorg.jboss.tools.quarkus.lsp4e.QuarkusLanguageServer.debugPort=1234`
> Provide the capability to debug MicroProfile LS by settings the debug port 

- .github/workflows/build_test.yml
- plugins/org.jboss.tools.quarkus.lsp4e/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.quarkus.lsp4e/pom.xml
- plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/ls/HtmlToPlainText.java
- plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/ls/JavaDoc2MarkdownConverter.java
reverting to old jsoup because of remark
fixes #213 
> fix application.properties completion
