features/pom.xml, plugins/pom.xml, pom.xml, site/pom.xml, tests/pom.xml
=> JBIDE-26816: Update bundles ids of the Quarkus plugins/feature to org.jboss.tools.quarkus.* - Rename 'parent' to 'quarkus'

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/project/ProjectUtils.java, plugins/org.jboss.tools.quarkus.runtime/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.runtime/build.properties, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/view/ExtensionsView.java, pom.xml, tests/org.jboss.tools.quarkus.runtime.test/src/org/jboss/tools/quarkus/runtime/VersionTest.java
=> JBIDE-26866: Update Quarkus dependency to release 0.23.0 - Update dependency to 0.21.0

plugins/org.jboss.tools.quarkus.runtime/META-INF/MANIFEST.MF, pom.xml, tests/org.jboss.tools.quarkus.runtime.test/src/org/jboss/tools/quarkus/runtime/VersionTest.java
=> JBIDE-26866: Update Quarkus dependency to release 0.23.0 - Update dependency to 0.22.0

pom.xml
=> #comment bump up to parent pom version = 4.13.0.Final-SNAPSHOT #close

plugins/org.jboss.tools.quarkus.runtime/META-INF/MANIFEST.MF, pom.xml, tests/org.jboss.tools.quarkus.runtime.test/src/org/jboss/tools/quarkus/runtime/VersionTest.java
=> JBIDE-26866: Update Quarkus dependency to release 0.23.0 - Update dependency to 0.23.0

plugins/org.jboss.tools.quarkus.runtime/META-INF/MANIFEST.MF, pom.xml, tests/org.jboss.tools.quarkus.runtime.test/src/org/jboss/tools/quarkus/runtime/VersionTest.java
=> JBIDE-26866: Update Quarkus dependency to release 0.23.2

plugins/org.jboss.tools.quarkus.runtime/META-INF/MANIFEST.MF, pom.xml, tests/org.jboss.tools.quarkus.runtime.test/src/org/jboss/tools/quarkus/runtime/VersionTest.java
=> JBIDE-26898: Update Quarkus dependency to release 0.25.0

site/category.xml
=> JBIDE-26942: include com.redhat.quarkus.jdt.core in site

pom.xml
=> Switch parent to 4.14.0.AM1

features/org.jboss.tools.quarkus.feature/feature.xml, site/category.xml
=> JBIDE-26863: added missing dependency to feature

features/org.jboss.tools.quarkus.feature/feature.xml, plugins/org.jboss.tools.quarkus.lsp4e/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.lsp4e/plugin.xml, plugins/org.jboss.tools.quarkus.lsp4e/pom.xml, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageClient.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageServer.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/JDTUtils.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/JDTUtilsImpl.java, pom.xml
=> JBIDE-26982: Switch to new microfile based quarkus ls

plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectExtensionsWizardPage.java
=> JBIDE-26985: Quarkus wizard enhancements

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusExtension.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectExtensionsWizardPage.java, tests/org.jboss.tools.quarkus.core.test/resources/single-preview-extension.json, tests/org.jboss.tools.quarkus.core.test/resources/single-stable-extension.json, tests/org.jboss.tools.quarkus.core.test/src/org/jboss/tools/quarkus/core/code/model/QuarkusExtensionsTest.java
=> JBIDE-26983: Display preview extensions as preview

plugins/org.jboss.tools.quarkus.lsp4e/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.lsp4e/build.properties, plugins/org.jboss.tools.quarkus.lsp4e/pom.xml, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/AbstractJavaDocConverter.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/HtmlToPlainText.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/JDTJavadocContentAccess.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/JDTUtilsImpl.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/JavaDoc2MarkdownConverter.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/JavaDoc2PlainTextConverter.java
=> JBIDE-26992: Implement Javadoc retrieval

site/category.xml
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
=> JBIDE-27001 Changing update site label to Quarkus(was OpenShift)

plugins/org.jboss.tools.quarkus.lsp4e/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.lsp4e/plugin.xml, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageClient.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageServer.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/OpenBrowserHandler.java
=> JBIDE-26976: add support for clickable codelens

features/org.jboss.tools.quarkus.test.feature/feature.xml, itests/org.jboss.tools.quarkus.integration.tests/.gitignore, itests/org.jboss.tools.quarkus.integration.tests/META-INF/MANIFEST.MF, itests/org.jboss.tools.quarkus.integration.tests/build.properties, itests/org.jboss.tools.quarkus.integration.tests/plugin.properties, itests/org.jboss.tools.quarkus.integration.tests/pom.xml, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/QuarkusIntegrationTests.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/common/PerspectiveTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/CreateNewProjectTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/InstallQuarkusExtensionTest.java, itests/pom.xml, pom.xml, test-framework/org.jboss.tools.quarkus.reddeer/.gitignore, test-framework/org.jboss.tools.quarkus.reddeer/META-INF/MANIFEST.MF, test-framework/org.jboss.tools.quarkus.reddeer/build.properties, test-framework/org.jboss.tools.quarkus.reddeer/pom.xml, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/common/QuarkusLabels.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/perspective/QuarkusPerspective.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/view/ExtensionsView.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/wizard/CodeProjectExtensionsWizardPage.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/wizard/CodeProjectInfoWizardPage.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/wizard/CodeProjectTypeWizardPage.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/wizard/CodeProjectWizard.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/wizard/QuarkusWizard.java, test-framework/pom.xml
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
=> JBIDE-26977 Initial Quarkus integration tests

plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectWizardController.java
=> JBIDE-27037: Permission denied when trying to run a Quarkus project on OSX

plugins/org.jboss.tools.quarkus.core/plugin.xml
=> JBIDE-27043: Rename Quarkus Launch Configuration to Quarkus Application

pom.xml
=> JBIDE-27053: update quarkus tooling to 0.0.5 release

itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/CreateNewProjectTest.java
Added test for new quarkus gradle project and check problems view.
Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>
=> JBIDE-27056

plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectExtensionsWizardPage.java
fixing UI issues on RHEL , lists were not visibles on the third wizard page.
=> JBIDE-27052: fix rendering issues on linux OS

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/project/ProjectUtils.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/launch/QuarkusProjectTab.java
=> JBIDE-27058: Run configuration fails for multi-module setup

itests/org.jboss.tools.quarkus.integration.tests/META-INF/MANIFEST.MF, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/QuarkusIntegrationTests.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/AbstractLaunchConfigurationTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/CreateNewQuarkusConfigurationGradleTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/CreateNewQuarkusConfigurationMavenTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/CreateNewProjectTest.java, test-framework/org.jboss.tools.quarkus.reddeer/META-INF/MANIFEST.MF, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/common/QuarkusLabels.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/ui/launch/QuarkusLaunchConfigurationTabGroup.java
=> JBIDE-27065: added CreateNewQuarkusConfigurationMavenTest and CreateNewQuarkusConfigurationGradleTest, changed MANIFEST.MF and QuarkusIntegrationTests

plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageClient.java
=> JBIDE-27136: Add support for Java code actions

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusExtension.java, plugins/org.jboss.tools.quarkus.ui/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectExtensionsWizardPage.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/QuarkusExtension2StringConverter.java
=> JBIDE-26984: Implement extension guide link

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusExtension.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectModel.java, tests/org.jboss.tools.quarkus.core.test/resources/single-extension-with-default.json, tests/org.jboss.tools.quarkus.core.test/resources/single-extension-without-default.json, tests/org.jboss.tools.quarkus.core.test/src/org/jboss/tools/quarkus/core/code/model/QuarkusExtensionsTest.java
=> JBIDE-26989: pre select default extensions

plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageClient.java
=> JBIDE-27200: Build failed on jbosstools-quarkus_master

itests/org.jboss.tools.quarkus.integration.tests/META-INF/MANIFEST.MF, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/QuarkusIntegrationTests.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/common/ApplicationPropertiesContentAssistTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/InstallQuarkusExtensionTest.java
=> JBIDE-27130:Created test for Content Assistant in application.properties

plugins/org.jboss.tools.quarkus.lsp4e/pom.xml
=> JBIDE-27271: Switch to microprofile-ls 0.8.0

plugins/org.jboss.tools.quarkus.core/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/QuarkusCoreUsageStats.java, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/launch/QuarkusLaunchConfigurationDelegate.java, plugins/org.jboss.tools.quarkus.lsp4e/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageServer.java
=> JBIDE-26911: add reporting to jbosstools-quarkus

tests/org.jboss.tools.quarkus.lsp4e.test/META-INF/MANIFEST.MF
- Adapt to the changes in upstream tests
=> JBIDE-27293: Quarkus build is broken

itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/QuarkusIntegrationTests.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/AbstractContentAssistantTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/AbstractLaunchConfigurationTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/CreateNewQuarkusConfigurationGradleTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/CreateNewQuarkusConfigurationMavenTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/CreateNewProjectTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/InstallQuarkusExtensionTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithDebugTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/universal/methods/AbstractQuarkusTest.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/common/QuarkusLabels.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/ui/launch/QuarkusLaunchConfigurationTabGroup.java
=> JBIDE-27212: Created test for run Quarkus Project with debug

plugins/org.jboss.tools.quarkus.lsp4e/pom.xml, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageServer.java
=> JBIDE-27357: Switch to microprofile-ls split

plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectExtensionsWizardPage.java
=> JBIDE-27363:     Selected extensions column is not visible by default

plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectExtensionsWizardPage.java
=> made lists in Quarkus extensions wizard page scrollable (JBIDE-27002)

features/org.jboss.tools.quarkus.feature/feature.xml, plugins/org.jboss.tools.quarkus.cheatsheet/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.core/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.runtime/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.ui/META-INF/MANIFEST.MF, pom.xml, tests/org.jboss.tools.quarkus.lsp4e.test/pom.xml
=> JBIDE-27453: Fix build after TP 4.17.0.AM1 update for 2020-09 RC1

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/project/ProjectUtils.java, plugins/org.jboss.tools.quarkus.lsp4e/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.lsp4e/plugin.xml, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusYAMLDocumentSetupParticipant.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/yaml/SchemaRegistry.java
=> Add support for application.yaml

plugins/org.jboss.tools.quarkus.lsp4e/pom.xml, pom.xml
=> JBIDE-27484: quarkus build is failing because of the GA/Final check

pom.xml
=> JBIDE-27488: Use release bits from LSP4MP and quarkus-ls

features/org.jboss.tools.quarkus.feature/feature.xml, features/org.jboss.tools.quarkus.test.feature/feature.xml
=> JBIDE-27500: Quarkus feature should be renamed to Quarkus Tools

itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/QuarkusIntegrationTests.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/AbstractContentAssistantTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/ApplicationPropertiesContentAssistTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/ApplicationPropertiesNewExtensionContentAssistTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/AbstractLaunchConfigurationTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/CreateNewProjectTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/InstallQuarkusExtensionTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithDebugTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/universal/methods/AbstractQuarkusTest.java
* Does it work? https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/quarkus-itests/184/
=> Jbide 27520

itests/org.jboss.tools.quarkus.integration.tests/META-INF/MANIFEST.MF, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/QuarkusIntegrationTests.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/application/yaml/ApplicationYaml.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/AbstractLaunchConfigurationTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithDebugTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithProfileTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/universal/methods/AbstractQuarkusTest.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/common/QuarkusLabels.java, test-framework/org.jboss.tools.quarkus.reddeer/src/org/jboss/tools/quarkus/reddeer/ui/launch/QuarkusLaunchConfigurationTabGroup.java
* Does it work? https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/quarkus-itests/246/
=> JBIDE-27465: Added ApplicationYaml test

plugins/org.jboss.tools.quarkus.lsp4e/plugin.xml, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageServer.java
@jkopriva @odockal wanted to add a unit test but don't know how to deal with
- double click
- code mining in text editor
=> JBIDE-27534: codeLens / codeMining does not work any more

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/QuarkusCoreConstants.java, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusModelRegistry.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectInfoWizardPage.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectModel.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectWizardController.java
=> JBIDE-27573: Support codestart option in project wizard

itests/org.jboss.tools.quarkus.integration.tests/resources/helloCommandoProject.txt, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/QuarkusIntegrationTests.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/application/yaml/ApplicationYaml.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/AbstractContentAssistantTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/ApplicationPropertiesContentAssistTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/ApplicationPropertiesNewExtensionContentAssistTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/AbstractLaunchConfigurationTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/CreateNewQuarkusConfigurationMavenTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/CreateNewProjectTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/InstallQuarkusExtensionTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithDebugTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithProfileTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/universal/methods/AbstractQuarkusTest.java
=> JBIDE-27582: reworked Quarkus test given new quarkus project

itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/QuarkusIntegrationTests.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/application/yaml/ApplicationYaml.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/AbstractContentAssistantTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/content/assistant/ApplicationPropertiesNewExtensionContentAssistTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/CodestartTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/universal/methods/AbstractQuarkusTest.java
=> JBIDE-27643: Create test for codestart Quarkus

features/pom.xml, tests/org.jboss.tools.quarkus.runtime.test/pom.xml, tests/org.jboss.tools.quarkus.ui.test/pom.xml
=> JBIDE-27614: fix source feature generation and temporary disable tests

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/launch/QuarkusLaunchConfigurationDelegate.java
=> JBIDE-27640: Quarkus Plugin doesn't let configure debug port

plugins/org.jboss.tools.quarkus.core/META-INF/MANIFEST.MF, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/QuarkusCoreConstants.java, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/QuarkusCorePlugin.java, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusModelRegistry.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectWizardController.java, tests/org.jboss.tools.quarkus.core.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.quarkus.core.test/src/org/jboss/tools/quarkus/core/code/model/QuarkusModelRegistryTest.java
=> JBIDE-27674: use POST in Quarkus wizard

itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/QuarkusIntegrationTests.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/application/yaml/ApplicationYaml.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/AbstractLaunchConfigurationTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectWithProfileTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectsOnOtherPorts.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/universal/methods/AbstractQuarkusTest.java
=> JBIDE-27657: Create test for run few Quarkus Projects on other ports

pom.xml, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/JDTJavaHoverTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/faulttolerance/JDTMicroProfileFaultToleranceJavaDefinitionTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/faulttolerance/JDTMicroProfileFaultToleranceJavaDiagnosticsTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/faulttolerance/JDTMicroProfileFaultTolerancePropertiesTest.java
=> JBIDE-27713: quarkus build failing with 2021-03 TP

tests/org.jboss.tools.quarkus.runtime.test/pom.xml, tests/org.jboss.tools.quarkus.ui.test/pom.xml
=> reverting temporary issue with Junit tests

plugins/org.jboss.tools.quarkus.lsp4e/META-INF/MANIFEST.MF, pom.xml
=> JBIDE-27780: Use released bits from LSP4MP and quarkus-ls for GA

.github/workflows/build_test.yml, .github/workflows/publish_reports.yml
=> Introduce GitHub Actions PR Check workflow, fixes JBIDE-27706

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/launch/QuarkusLaunchConfigurationDelegate.java
=> JBIDE-27802: JAVA_HOME should not be visible in environment list

features/org.jboss.tools.quarkus.feature/feature.xml, pom.xml
=> JBIDE-27861: Use upstream released bits for Final/GA

itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/environment/AbstractEnvironmentVariablesTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/AbstractLaunchConfigurationTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/CreateNewQuarkusConfigurationGradleTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/launch/configuration/CreateNewQuarkusConfigurationMavenTest.java, itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/RunProjectsOnOtherPorts.java
Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>
=> JBIDE-27920: Reworked runNewQuarkusConfiguration and related

features/org.jboss.tools.quarkus.feature/feature.xml
=> JBIDE-28052: Code completion does not work for Java files

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/QuarkusCoreConstants.java, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusExtensionsModel.java, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusModel.java, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusModelRegistry.java, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusStream.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectModel.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectTypeWizardPage.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectWizardController.java, tests/org.jboss.tools.quarkus.core.test/src/org/jboss/tools/quarkus/core/code/model/QuarkusExtensionsModelTest.java, tests/org.jboss.tools.quarkus.core.test/src/org/jboss/tools/quarkus/core/code/model/QuarkusExtensionsTest.java, tests/org.jboss.tools.quarkus.core.test/src/org/jboss/tools/quarkus/core/code/model/QuarkusModelRegistryTest.java, tests/org.jboss.tools.quarkus.ui.test/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectWizardControllerTest.java, tests/org.jboss.tools.quarkus.ui.test/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectWizardModelTest.java
=> JBIDE-27973: Add stream selection to the project wizard

itests/org.jboss.tools.quarkus.integration.tests/src/org/jboss/tools/quarkus/integration/tests/project/universal/methods/AbstractQuarkusTest.java
Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>
=> JBIDE-28164: Added workaround for Integration test (create new quarkus project)

plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/yaml/SchemaRegistry.java
=> JBIDE-28185: Random NPE when computing JSON schemas

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/tool/GradleToolSupport.java, plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/tool/MavenToolSupport.java
=> JBIDE-28213: Quarkus project profile doesn't work

.github/workflows/build_test.yml
=> master -> main in github workflows

pom.xml, tests/org.jboss.tools.quarkus.lsp4e.qute.test/pom.xml
=> JBIDE-28409: fix Quarkus build

plugins/org.jboss.tools.quarkus.lsp4e/pom.xml, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/JDTJavaHoverTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/faulttolerance/JDTMicroProfileFaultToleranceJavaDefinitionTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/faulttolerance/JDTMicroProfileFaultToleranceJavaDiagnosticsTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/faulttolerance/JDTMicroProfileFaultTolerancePropertiesTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/health/JDTJavaDiagnosticsMicroProfileHealthTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/jaxrs/JDTJaxRsCodeLensTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/metrics/JDTMicroProfileMetricsTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/opentracing/JDTMicroProfileOpenTracingTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/restclient/JDTJavaCodeLensMicroProfileRestClientTest.java, tests/org.jboss.tools.quarkus.lsp4e.test/src/main/java/org/jboss/tools/quarkus/lsp4e/core/restclient/JDTJavaDiagnosticsMicroProfileRestClientTest.java
=> JBIDE-28427: Can't open Quarkus properties files

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusExtension.java, tests/org.jboss.tools.quarkus.core.test/src/org/jboss/tools/quarkus/core/code/model/QuarkusExtensionsTest.java
=> JBIDE-28447: Quarkus extension tags format has changed

plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/handlers/qute/OpenJavaDefinitionHandler.java
=> JBIDE-28451: Navigation from Qute template to a method does not work

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/code/model/QuarkusModel.java, plugins/org.jboss.tools.quarkus.ui/src/org/jboss/tools/quarkus/ui/wizard/CodeProjectExtensionsWizardPage.java
=> JBIDE-28495: Quarkus wizard exceptions added to log

plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/qute/QuteProjectListener.java
=> JBIDE-28438: Redesign QuteProjectListener

plugins/org.jboss.tools.quarkus.core/src/org/jboss/tools/quarkus/core/QuarkusCoreUsageStats.java, plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/ls/qute/QuteLanguageServer.java
=> JBIDE-28505: Report Qute LS telemetry as a specific event

plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/internal/ls/JDTUtilsImpl.java, pom.xml, tests/org.jboss.tools.quarkus.core.test/META-INF/MANIFEST.MF
=> JBIDE-28815: Fix after TP update

pom.xml
=> JBIDE-28975 : fix integration tests

documentation/building/build.md
Tried to build the repo...couldn't... figured out how by browsing the org's repos ..sharing the knowledge.
=> Link to devdoc repo
